### ISSUE TITLE
.NET examples

### ISSUE THREAD

**Issue by flieks** [OData/vocabularies#24]
I can't find any .NET examples for implementing these shared vocabularies. I want to use the Display vocabulary.

Trying to implement something i posted on the [OData/WebApi](https://github.com/OData/WebApi/issues/1573) issues but maybe this is a better place to ask..

**Comment by Danielku15** [comment]
I found this StackOverflow article lately: https://stackoverflow.com/a/27414874/996233

The post describes it like this: 
```cs
ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
var model = builder.GetEdmModel() as EdmModel;
model.SetVocabularyAnnotation(
    new EdmAnnotation(model.EntityContainer.FindEntitySet("People").EntityType().FindProperty("FullName"),
    new EdmTerm("Org.OData.Core.V1", "Computed", EdmPrimitiveTypeKind.Boolean),
    new EdmBooleanConstant(true)));

```

For me the code needed to look a bit different: 

```cs
var annotatable = model.EntityContainer.FindEntitySet("People").EntityType().FindProperty("FullName"); 
model.SetVocabularyAnnotation(new EdmVocabularyAnnotation(annotatable, CoreVocabularyModel.ComputedTerm, new EdmBooleanConstant(true)));
```

**Comment by xuzhg** [comment]
@Danielku15 Thanks for sharing the findings. 

Besides, in the OData.net EDM test projects, there's a bunch of test codes related to vocabulary annotation. 
For example: https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Microsoft.OData.Edm.Tests/Csdl/CsdlWriterTests.cs#L26-L49
