### ISSUE TITLE
Port standardized vocabularies to this repo

### ISSUE THREAD

**Issue by markdstafford** [OData/vocabularies#6]
It would be very convenient to have a copy of the [core vocabulary](http://docs.oasis-open.org/odata/odata/v4.0/os/vocabularies/Org.OData.Core.V1.xml) and the [capabilities vocabulary](http://docs.oasis-open.org/odata/odata/v4.0/os/vocabularies/Org.OData.Capabilities.V1.xml) stored here alongside the community vocabularies. Port the vocabularies here and add .md documentation.

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
I added Core and Capabilities in PR #10
Writing the documentation for these could take a little bit of time. Anyone interested can start on that.

**Comment by markdstafford** [comment]
Completed by @MrTomWhite's commit: 375ab123ac6d621b11bf52e7d742d5677fd6135c.
